language: rust
rust:
  - stable

cache: cargo

os: linux
dist: focal

before_script:
  - rustup target add thumbv6m-none-eabi
  - cargo install flip-link

script:
  - cargo build --release
  - sha256sum ./target/thumbv6m-none-eabi/release/tc2-firmware | cut -d ' ' -f 1 > ./target/thumbv6m-none-eabi/release/tc2-firmware.sha256

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - "./target/thumbv6m-none-eabi/release/tc2-firmware"
    - "./target/thumbv6m-none-eabi/release/tc2-firmware.sha256"
  skip_cleanup: true
  on:
    tags: true
