language: rust
rust:
  - stable

cache: cargo

os: linux
dist: bionic

before_script:
  - rustup target add thumbv6m-none-eabi

script:
  - cargo build --release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - "./target/thumbv6m-none-eabi/release/tc2-firmware"
  skip_cleanup: true
  on:
    tags: true
