name: Rust CI and release

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.90.0 # If changing this also change the `rust-toolchain.toml`
          override: true
          components: rustfmt, clippy

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Add target for cross-compilation
        run: rustup target add thumbv6m-none-eabi

      - name: Install flip-link
        run: cargo install flip-link

      - name: Build the project
        run: cargo build --release --target=thumbv6m-none-eabi

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --workspace --features std --no-default-features --target=x86_64-unknown-linux-gnu --package tc2-firmware --test tests::testing::low_power__fixed_window__audio_or_thermal

      - name: Generate SHA256 checksum
        run: sha256sum ./target/thumbv6m-none-eabi/release/tc2-firmware | cut -d ' ' -f 1 > ./target/thumbv6m-none-eabi/release/tc2-firmware.sha256

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./target/thumbv6m-none-eabi/release/tc2-firmware
            ./target/thumbv6m-none-eabi/release/tc2-firmware.sha256
          allowUpdates: true
